### ISSUE TITLE
Can't install binfmt-support.

### ISSUE THREAD

**Issue by DDoSolitary** [alpinelinux/alpine-chroot-install#10]
This is the error I got when running on AppVeyor

```
E: Package 'binfmt-support' has no installation candidate
```

The problem doesn't exist on Travis because it has `binfmt-support` already installed, but it's not the case on AppVeyor. I think the `-o xxx` in this [line](https://github.com/alpinelinux/alpine-chroot-install/blob/1ef7dfbcd2651de521b127d6d70459162606cfd4/alpine-chroot-install#L211) should be removed because it makes apt-get ignore the packages from the current release.

**Comment by DDoSolitary** [comment]
Removing this will still allow the script to install the newer qemu-user-static because the source list added is in `/etc/apt/sources.list.d`, where apt-get reads by default.

**Comment by jirutka** [comment]
I’ve removed support for installing qemu-user-static from a different repository added by the script, so this is not relevant anymore. Please commit message 2361b526ed2cfe20dbe6e262bbd3c6a7d6af88ed for details.
