### ISSUE TITLE
Post install documentation?

### ISSUE THREAD

**Issue by jedahan** [alpinelinux/alpine-chroot-install#11]
Let's say I have access to a remote machine with some other distro on it, and I want to install and then boot into alpine linux.

Install with this script is great, but theres definitely some extra work to be done to get into boot, and its kinda hard to know what is needed and not looking at the wiki.

ex:
* should setup-disk be run?
* can I just edit the existing boot config to point root = to the new partition?
etc...

Thanks!

**Comment by jirutka** [comment]
> but theres definitely some extra work to be done to get into boot

Indeed, but that's not intended use case of this script. You can find some hints in https://wiki.alpinelinux.org/wiki/Chroot.
