### ISSUE TITLE
Fedora?

### ISSUE THREAD

**Issue by Suppresed** [alpinelinux/alpine-chroot-install#12]
The usage of apt-get  prevents me from using this.

**Comment by jirutka** [comment]
[alpine-chroot-install:9-11](https://github.com/alpinelinux/alpine-chroot-install/blob/1ef7dfbcd2651de521b127d6d70459162606cfd4/alpine-chroot-install#L9-L11):

> If qemu-user and binfmt is needed, the script checks if both are available
> and qemu-user has version >= 2.6. If not, it tries to install them using
> apt-get. Beside this the script should work on any Linux system.

So if you run it on Fedora **and** you need to emulate a different architecture than you run on your host (e.g. aarch64 on x86_64), then you just have to just install `qemu-user` and `binfmt` yourself and everything should work. There's no other dependency on apt-get.
