### ISSUE TITLE
build raspberry pi image

### ISSUE THREAD

**Issue by hoshsadiq** [alpinelinux/alpine-chroot-install#15]
Hi,

I'm curious as to what the best way is to build a customised alpine image for the raspberry pi using this. Specifically, once I'm done with the customisation, what's the best way to move this over to an sd cars?

**Comment by dangerousHobo** [comment]
Hi @hoshsadiq,
I'm curious to how you completed this. Did you use the `alpine-chroot-install` script, the `alpine-make-rootfs` script, or something else?

**Comment by hoshsadiq** [comment]
I used the `alpine-chroot-install`. I'm working on it still,  but I've got the initial code done. Currently trying to build a few pipelines around it.

The code lives at https://github.com/hoshsadiq/alpine-raspberry-pi . Specifically the file script make-image that does the heavily lifting and creates an image. The plan is to use packer to further customise the image.
