### ISSUE TITLE
Bump to QEMU_UBUNTU_REL='bionic'

### ISSUE THREAD

**Issue by knoopx** [alpinelinux/alpine-chroot-install#17]
Artful Aardvark reached end of life and is no longer available in Ubuntu archives, causing the script to fail if QEMU version is lower than required.

**Comment by jirutka** [comment]
I’ve changed it but now it fails with quite weird error:

```
The following NEW packages will be installed:

  qemu-user-static

0 upgraded, 1 newly installed, 0 to remove and 747 not upgraded.

Need to get 9,979 kB of archives.

After this operation, 101 MB of additional disk space will be used.

Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 qemu-user-static amd64 1:2.11+dfsg-1ubuntu7 [9,979 kB]

Fetched 9,979 kB in 0s (72.1 MB/s)

dpkg-deb: error: archive '/var/cache/apt/archives/qemu-user-static_1%3a2.11+dfsg-1ubuntu7_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up

dpkg: error processing archive /var/cache/apt/archives/qemu-user-static_1%3a2.11+dfsg-1ubuntu7_amd64.deb (--unpack):

 subprocess dpkg-deb --control returned error exit status 2

Errors were encountered while processing:

 /var/cache/apt/archives/qemu-user-static_1%3a2.11+dfsg-1ubuntu7_amd64.deb

E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Do you have any idea what’s going on?

**Comment by knoopx** [comment]
Works fine from ubuntu 16.04 (using it here https://github.com/knoopx/alpine-raspberry-pi), what version is failing for you?

**Comment by nrybowski** [comment]
From https://travis-ci.org/alpinelinux/alpine-chroot-install/jobs/572038464#L395, it seems that the missing key provoke the mentioned error.
The Ubuntu version used in the travis seems also to be a [problem ](https://travis-ci.org/nrybowski/alpine-chroot-install/builds/598238343)

**Comment by nrybowski** [comment]
I think it's a good idea. Maybe it could be interesting to [embed nix into the script](https://nixos.org/nix/download.html) ? It will act as a standalone package manager regardless of the one of the underlying distribution so the script will become more portable and we get rid of the versioning problem of Ubuntu.

**Comment by jirutka** [comment]
Okay, I removed the code for installing QEMU from Ubuntu repository in 2361b526ed2cfe20dbe6e262bbd3c6a7d6af88ed.

I know nix, but it would be massive overkill for this simple script.
