### ISSUE TITLE
[v0.11.0] Alpine setup broken in travis build

### ISSUE THREAD

**Issue by nrybowski** [alpinelinux/alpine-chroot-install#19]
I made a [quick and dirty fix](https://github.com/nrybowski/apk-tools/blob/b0b50bcc5893406feb2ebc673f73550c8e668868/.travis.yml#L16) but [functional](https://travis-ci.org/nrybowski/apk-tools/builds/598251534) in the travis.yml of apk-tools (using v0.7.0) but when I try to update to the latest release of alpine-chroot-install (v0.11.0) the [setup of Alpine fails](https://travis-ci.org/nrybowski/apk-tools/jobs/599159710#L193).

**Comment by nrybowski** [comment]
libfetch was [removed in aports v3.9](https://github.com/alpinelinux/aports/commit/8beba74a1a40f0edc45424a7bdba90a3131a42d0). [v0.7.0 was using v3.6 ](https://github.com/alpinelinux/alpine-chroot-install/blob/v0.7.0/alpine-chroot-install#L258) and [v0.11.0 is using v3.10](https://github.com/alpinelinux/alpine-chroot-install/blob/v0.11.0/alpine-chroot-install#L273) as default branch. Is libfetch-dev still useful in the script ?

**Comment by jirutka** [comment]
I fixed it now, the build finally [passes](https://travis-ci.org/alpinelinux/apk-tools/builds/611344120) on [apk-tools](https://github.com/alpinelinux/apk-tools).
