### ISSUE TITLE
APK tools static binary

### ISSUE THREAD

**Issue by douglas-raillard-arm** [alpinelinux/alpine-chroot-install#32]
The current script dowloads: https://github.com/alpinelinux/apk-tools/releases/download/v2.10.4/apk-tools-2.10.4-x86_64-linux.tar.gz

This binary seems outdated (2019) and new releases do not include a binary anymore (only sources). Should alpine-chroot-install switch to a new provider ?

I found that: https://pkgs.org/search/?q=apk-tools-static which also handily provides an aarch64 variant of the binary, which I am interested in in addition to x86. This would provide an up-to-date version of apk and also close https://github.com/alpinelinux/alpine-chroot-install/issues/27

If that seems an acceptable solution I'm happy to make the PR to switch to that new source

**Comment by jirutka** [comment]
Upstream finally provides static binaries again, but on gitlab.alpinelinux.org instead of GitHub ([MR !70](https://gitlab.alpinelinux.org/alpine/apk-tools/-/merge_requests/70)).

Fixed in 847cab438e5f05eb0807488c3fa7f8836ca84078.
