### ISSUE TITLE
Is it possible to let enter-chroot return the exit code of the command being run?

### ISSUE THREAD

**Issue by DDoSolitary** [alpinelinux/alpine-chroot-install#4]
That would be really useful in a CI environment to determine whether the build succeeded or not.

**Comment by jirutka** [comment]
It should work in this way, exactly for this use case. So it’s a bug if it does not. I’ll look at it later.

**Comment by DDoSolitary** [comment]
It is my build script's fault. It didn't return the error code returned by abuild. Sorry.
